### ISSUE TITLE
package.json is missing consolidate dependency

### ISSUE THREAD

**Issue by ghost** [pasteit/pasteit#5]
When I run "node app.js" in the pasteit directory I get a stack trace indicating that the consolidate module is missing.

```bash
node app.js

Error: Cannot find module 'consolidate'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/manirew/Projects/pasteit/pasteit/app.js:8:12)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

**Comment by macskay** [comment]
Thanks

**Comment by macskay** [comment]
5bf463f9ccc90c20ef9b2f0b0be987eb263473d9
